# Site settings
title: Tox Blog
email: irungentoo@gmail.com
description: A new kind of Instant Messaging
url: "http://tox.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: Tox

# Build settings
markdown: kramdown
